### ISSUE TITLE
Evaluate AS PR 5070 (null prototype issue)

### ISSUE THREAD

**Issue by glasser** [apollographql/datasource-rest#67] opened 2022-10-18 23:43 UTC
We closed https://github.com/apollographql/apollo-server/pull/5070 to move it to this repository. We should look to see if the change is still applicable.

**Comment by aeddie-zapidhire** [comment] 2022-10-26 22:43
Ran into this yesterday. The main problem is it takes many hours to find out where the problem is. For the sake of Google indexing, my problem was seeing `[object Object]` as a string in the request received by the body whilst using `type-graphql`.

Temporary solutions are to:
a. convert the body data to a plain JavaScript object using something like `{ ...body }`
b. add a `toJSON` function to your object (your `@InputType` classes in TypeGraphQL)

The issue manifests in the `fetch` method of the `RESTDataSource` class where it is interrogating the `options.body` property.

**Comment by trevor-scheer** [comment] 2022-11-11 01:06
Closing this as a duplicate of #68 (which has a lot more context, and is also linked up to the PR I opened)

**Closed by trevor-scheer** 2022-11-11 01:06 UTC
